version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend   # 后端 Dockerfile
    ports:
      - "8000:8000"                   # 映射后端端口到主机
    environment:
      - ENV=production                # 环境变量指定
    volumes:
      - ./backend:/app/backend        # 挂载代码，方便开发时更新
    depends_on:
      - db                            # 依赖数据库服务

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend # 前端 Dockerfile
    ports:
      - "3000:3000"                   # 映射前端端口
    environment:
      - NODE_ENV=production           # Node.js 环境变量
    volumes:
      - ./frontend:/app/frontend      # 挂载代码

  db:
    image: postgres:15                # 使用 PostgreSQL 数据库镜像
    container_name: chatbot_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chatbot_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
